data:
  # name of the dataset
  name: airfoil
  # name of the section dataset
  sec_name: airfoil_sec_z_0.10
  # directory for storing the dataset
  dirt: ./dataset/airfoil/raw

ckpt:
  # name of checkpoint
  name: airfoil
  # directory for storing checkpoint
  dirt: ./checkpoint/airfoil/infer

log:
  # directory for saving log
  dirt: ./log/airfoil

output:
  # name of the dataset
  name: airfoil
  # directory for storing the dataset
  dirt: ./dataset/airfoil/output

# computing device
device: cuda