data:
  # name of the dataset
  name: airfoil
  # directory for storing the dataset
  dirt: ./dataset/airfoil/raw

model:
  # dimension of node input features
  node_dim: 5
  # dimension of edge input features
  edge_dim: 4
  # dimension of output
  output_dim: 6
  # number of hidden block
  block_num: 8
  # dimension of hidden layer
  hidden_dim: 64

train:
  # learinng rate
  lr: 0.0001
  # number of epochs
  epoch_num: 10000
  # decay step
  scheduler_step: 100
  # decay rate
  scheduler_gamma: 0.98

ckpt:
  # name of checkpoint
  name: airfoil
  # directory for storing checkpoint
  dirt: ./checkpoint/airfoil/train

log:
  # directory for saving log
  dirt: ./log/airfoil

output:
  # name of the dataset
  name: airfoil
  # directory for storing the dataset
  dirt: ./dataset/airfoil/output

# computing device
device: cuda