data:
  # name of the dataset
  name: cardiovascular
  # directory for storing the dataset
  dirt: ./dataset/cardiovascular/processed
  # rate noise
  noise_rate: 100
  # rate noise features
  noise_rate_feat: 0.00001
  # 0: min_max, 1: normal, 2: none
  label_norm: 1
  # boundary type
  bc_type: 'physiological'
  # normal type
  norm_type: 'normal'
  # batch size
  batch_size: 100

model:
  # dimension of node input
  input_dim_node: 18
  # dimension of edge input
  input_dim_edge: 9
  # dimension of output
  output_dim: 2
  # latent size gnn
  hidden_dim_gnn: 16
  # latent size mlps
  hidden_dim_mlp: 64
  # hidden layers mlps
  layer_num_mlp: 3
  # gnn layers
  layer_num_gnn: 3
  # stride for multistep training
  stride: 5

train:
  # learning rate
  lr: 0.001
  # learning rate decay
  lr_decay: 0.001
  # l2 regularization
  weight_decay: 0.00001
  # total number of epochs
  epoch_num: 3

output:
  # name of the output file
  name: cardiovascular
  # directory for storing the output file
  dirt: ./dataset/cardiovascular/output

log:
  # directory for saving log
  dirt: ./log/cardiovascular

# computing device
device: cpu