data:
  # name of the dataset
  name: flag_simple_valid
  # directory for storing the dataset
  dirt: ./dataset/flag_simple/raw
  # the node types that apply a mask
  node_type:
    - NORMAL

ckpt:
  # name of checkpoint
  name: flag_simple
  # directory for storing checkpoint
  dirt: ./checkpoint/flag_simple/infer

output:
  # name of the output file
  name: flag_simple
  # directory for storing the output file
  dirt: ./dataset/flag_simple/output
  # output image resolution.
  dpi: 150

log:
  # directory for saving log
  dirt: ./log/flag_simple

# computing device
device: cuda