data:
  # name of dataset
  name: pdbbind
  # directory for storing dataset
  dirt: ''
  # path for storing dataset
  path: ./dataset/pdbbind/inference/protein_ligand.csv
  # directory for storing cached dataset
  cache_dirt: ./dataset/pdbbind/processed/cache
  # directory for storing output file
  output_dirt: ./dataset/pdbbind/output/diffdock
  # path for storing LM embeddings for the receptor features
  esm_embd_dirt: ./dataset/pdbbind/processed/esm2_output
  
  # keeps the local structure when specifying an input with 
  # 3D coordinates instead of generating them with RDKit
  keep_local_structure: False
  # number of samples to generate
  sample_per_complex: 5

ckpt:
  # name of checkpoint
  name: pdbbind
  # directory for storing checkpoint
  dirt: ./checkpoint/pdbbind/infer

inference:
  sample_size: 6
  # number of denoising steps
  step_num: 10

log:
  # directory for saving log
  dirt: ./log/pdbbind

# computing device
device: cuda
# whether or not use parallel training
no_parallel: True