data:
  # name of the dataset
  name: qm9
  # directory for storing dataset
  dirt: ./dataset/qm9/raw
  # ratio for spliting dataset
  split_ratio: 0.8
  # max number of node in each graph
  node_num_max: 9
  # whether to rescale data to [-1,1]
  centralization: False
  # whether to add channel
  channelization: False
  # whether to remove diagonal in adjacency matrix
  remove_diagonal: False

  # batch size in training
  batch_size: 1024

model:
  # dimension of input of network x
  x_input_dim: 4
  # dimension of input of network adj
  adj_input_dim: 2
  # number of features
  features_num: 256
  # type of graph layer
  graph_layer_type: PosTransLayer
  # number of graph layer
  graph_layers_num: 4
  # number of channels
  channels_num: 1
  # type of activatioin function
  actv_type: silu

sde:
  # minimum beta
  beta_min: 0.1
  # maximum beta
  beta_max: 1.0

diffusion:
  # number of time steps in diffusion
  time_step_num: 1000

train:
  # learning rate
  lr: 0.005
  # decay rate
  lr_decay: 0.999
  # number of training epoch
  epoch_num: 100
  # number of warmup step
  warmup_step: 0
  # upper bound of norm for gradient clipping
  grad_clip: 0
  # whether use exponential moving average
  use_ema: False

log:
  # directory for saving log
  dirt: ./log/qm9

# device
device: cuda