import argparse


def parse_args():
    parser = argparse.ArgumentParser(description="Cylinder flow PINN runner")
    parser.add_argument("--mode", type=str, default="quick", choices=["quick", "train"])
    parser.add_argument("--data", type=str, default="simul", choices=["simul", "real"])
    parser.add_argument("--data_path", type=str, default="data/simul_cylinder_re100.mat")
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--time_window", type=int, default=10)
    parser.add_argument("--eval_snap", type=int, default=10)
    parser.add_argument("--hidden_size", type=int, default=120)
    parser.add_argument("--hidden_size_aux", type=int, default=20)
    parser.add_argument("--layers", type=int, default=6)
    parser.add_argument("--layers_aux", type=int, default=6)
    parser.add_argument("--n_train", type=int, default=15000)
    parser.add_argument("--n_boundary", type=int, default=4096)
    parser.add_argument("--quick_epochs", type=int, default=300)
    parser.add_argument("--train_epochs", type=int, default=50000)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--re", type=float, default=100.0)
    parser.add_argument("--lam_equ", type=float, default=10.0)
    parser.add_argument("--lam_bc", type=float, default=10.0)
    parser.add_argument("--lam_ic", type=float, default=10.0)
    parser.add_argument("--alpha_evm", type=float, default=0.03)
    parser.add_argument("--model_dir", type=str, default="model")
    parser.add_argument("--result_dir", type=str, default="results")
    parser.add_argument("--run_full_windows", action="store_true")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()
